<?php require("/var/www/techhounds-cms2/admin/util.php");?>
<html>
  <head>
    <meta charset="utf-8">
    <title>Documentation</title>
    <link rel="stylesheet" type="text/css" href="/admin/css/style.css">
  </head>
  <body>
    <div class="body-container">
<h1>Permissions</h1>
<h2>Introduction</h2>
<p>Tired of your team members screwing up your website? Tired of (accidentally) screwing yourself over?
Well, we have just the solution!!! With permissions, you can restrict what commands other people (and yourself!) can run.
You can even restrict what files they can modify and what user permissions they can change.</p>
<p>The user permissions are allow-default.
The main rules are each seperated by 2 newlines.</p>
<pre><code>&lt;rule 1&gt;

&lt;rule 2&gt;

...</code></pre>
<h2>Main Rules</h2>
<p>A page &amp; action pair is written like <code>&lt;page&gt;/&lt;action&gt;</code>.<br>
The default action is written as a blank after the slash.<br>
A list of pages &amp; actions can be found at the bottom of this document.<br>
<code>+</code> is used to indicate that a paticular page/action is allowed.<br>
<code>-</code> is used to indicate that a paticular page/action is not allowed.<br>
A line starting with anything else is considered a comment.<br>
<code>*</code> can be used anywhere and matches any number of characters.<br>
<code>?</code> can be used anywhere and matches exactly one character.</p>
<p>An example file is shown below. This example is not designed to be functional, it is only to demonstrate the various possible combinations.</p>
<pre><code>Forbids every action and every page
-*/*

Allows every action on the index page
+index/*

Allows actions ending in userpass on the users page
+users/*userpass

Allows the default action on the files page
+files/</code></pre>
<h2>Minor Rules</h2>
<p>Following each major rule, several minor rules can exist. They follow a similar format to major rules, but instead restrict what pages or users a user can access.<br>
Minor rule effects:</p>
<ul>
<li>users - restricts what users can be edited</li>
<li>files - restricts what dirs can be edited</li>
<li>dynamic - restricts what files can be edited</li>
<li>static - restricts what files can be edited</li>
<li>upload - restricts what dirs can be uploaded to</li>
</ul>
<p><code>+</code> Allows that paticular user/dir/file.
<code>-</code> Forbids that paticular user/dir/file.
A line starting with anything else is considered a comment.
Wildcards may also be used here.</p>
<p>An example file is shown below. This example is not designed to be functional, it is only to demonstrate the various possible combinations.</p>
<pre><code>Allows editing of dynamic files
+dynamic/*
Disallows editing of all php files
-*.php
Allows all files named index.php
+index.php
Disallows editing index.php only in the root directory
-/index.php</code></pre>
<h2>List of pages and actions</h2>
<ul>
<li>index
<ul>
<li>[default] - the main page</li>
<li>purge - deletes all autogenerated files</li>
<li>regenerate - regenerates all autogerated files</li>
<li>hash - creates a hash of every file</li>
<li>backup - creates a backup of every file</li>
<li>restore - restores the backup of every file</li>
<li>regendoc - generates the html version of the documentation</li>
</ul></li>
<li>login
<ul>
<li>[default] - login page</li>
<li>logout - logout page</li>
</ul></li>
<li>users
<ul>
<li>[default] - lists all the users</li>
<li>adduser - creating an user</li>
<li>s_adduser - saving an added user</li>
<li>userpass - changing someone's username and password</li>
<li>s_userpass - saving changes to someone's username and password</li>
<li>perms - changing someone's permissions</li>
<li>s_perms - saving changes to someone's permissions</li>
<li>delete - deleting a user</li>
</ul></li>
<li>files
<ul>
<li>[default] - lists all the files in a dir</li>
<li>newdir - creates a new dir</li>
<li>newstatic - creates a new static file</li>
<li>newdynamic - create a new dynamic file</li>
<li>roc - renames or copies a file or dir</li>
<li>switchview - switches between simple view and advanced view</li>
</ul></li>
<li>static
<ul>
<li>[default] - edits a static file</li>
<li>save - saves a static file</li>
</ul></li>
<li>dynamic
<ul>
<li>[default] - edits a dynamic file</li>
<li>save - svaes a dynamic file and generates the autogenerated page</li>
</ul></li>
<li>upload
<ul>
<li>[default] - uploads files to a dir</li>
</ul></li>
<li>error
<ul>
<li>[default] - shows the tail of the error log</li>
</ul></li>
<li>permissions
<ul>
<li>[default] - shows a user's permissions, also the permission denied page</li>
</ul></li>
</ul>
<p><a href="index.php">Back</a></p>
    </div>
  </body>
</html>
